### PR TITLE
add trash operation example

### PR DESCRIPTION
**Pull request by tabacitu**
### BEFORE - What was wrong? What was happening before this PR?

No example for https://github.com/Laravel-Backpack/PRO/pull/96

### AFTER - What is happening after this PR?

Yes example

---

Note: needs that feature to be merged and tagged, obviously.

### CODE REVIEW

**Comment by jorgetwgroup** [comment]
Hi there @tabacitu first, happy new year!

I check the example, this work, just trash operation have small bug need to be fix.

This is ready.

Cheers.

**Comment by pxpm** [comment]
Hey guys, I couldn't make this work without adding `->onDelete('cascade')` in the `pet_id` foreign column definition on passports table or removing the foreign key.
```diff
Schema::create('passports', function (Blueprint $table) {
- $table->foreignId('pet_id')->constrained();
+ $table->foreignId('pet_id')->constrained()->onDelete('cascade');
});
```
Can any of you guys confirm that ? @jorgetwgroup @tabacitu @karandatwani92 ? It seemd it worked fine for you guys, so probably some database configuration ? I am using Mysql 8.0

Cheers

**Comment by jorgetwgroup** [comment]
Hi @pxpm this is right, delete didnt work, just trash and filter is working normal.

screenshot-backpack test-2023 01 17-15_13_58

Please check @karandatwani92 

Cheers.

**Comment by tabacitu** [comment]
@karandatwani92 I know there have been changes to TrashOperation since this PR was last looked at. Could you please take another look, make sure it works on in the Demo? If so, give me or Pedro the thumbs-up to merge - we really should have TrashOperation featured in the demo.

**Comment by karandatwani92** [comment]
**OK Tested**, All three operations (trash, destroy, restore) are perfectly working.
Make sure to run `php artisan migrate:fresh` which adds `->constrained()->onDelete('cascade');` to passports table.

**Pull request merged**
