### PR TITLE
Laravel 8 database seeders factories

### PR DESCRIPTION
**Pull request by promatik**
@tabacitu this is related to #190.
Renaming seeder folder is not enough, we have to add it to composer autoload.

Since I've done this migration before, it was easier to do it again for this project.
Laravel 8 uses `HasFactories` trait on Models, so everything should be more organized by default, I moved factories from `ModelFactory.php` to each model proper factory.
For doing this I had to create some models, like `Article` or `Category` that the only thing it does is to extend the original model, and use the `HasFactories` Trait.

This is kind of a huge change 😬 so I created this new PR, and I'll let you guys decide if we opt for this or not.

### CODE REVIEW

**Comment by tabacitu** [comment]
@promatik a lot of time has passed and I forgot why we needed this 😅 Could you please rephrase this or refresh my mind?

Thanks!

**Comment by promatik** [comment]
Exactly @tabacitu, but maybe some of this changes should be done directly to the packages, `Article`, `Tag`, `Category` Model on NewsCRUD and `MenuItem` could have the `HasFactory` there, on its packages, instead of doing the override on demo.

This came up because of https://github.com/Laravel-Backpack/demo/pull/190.

This makes everything more organized because each entity has it's own seeder and factory, L8 style.

Let me know what you think about the `HasFactory`.

**Comment by tabacitu** [comment]
@promatik heads-up, I think you'll be happy to know I finally merged this. Had to do the same for the new entities and reconcile the differences with Pedro's PR, but I think it's a change in the right direction, I agree. No point in using the old factories any more.

About creating a new model just for the `HasFactory` trait... is that really needed? AFAIK that provides just one thing - the ability to do `User::factory()`... but we should be able to call the factory directly too, right? Just not from the model. And that would strip out quite a few files from this.

Food for thought.

**Comment by promatik** [comment]
Wow! Nice @tabacitu, I agree, this is a step in the right direction 👌

Regarding the models with just "use HasFactory", yes! we could strip this files, I though this way stuff would be more clean (somehow), by following the same pattern/code on the factories, and by having all the models used by the demo in the Models folder, even if those files mainly point to the original models. Maybe it's also a way for beginners to understand where the models are 🤷‍♂️

But I agree it adds a lot of unnecessary files...

**Comment by tabacitu** [comment]
Another way to get rid of those extra files would be to... you know... add HasFactory on the Models in all those packages? 🤷‍♂️😅

Is there any downside to doing this? It looks to me like that trait only includes a getter and a resolver soo... it should be fine to have HasFactory, even if there is no factory... correct?

**Pull request merged**
