### PR TITLE
fixes api response from charts

### PR DESCRIPTION
**Pull request by pxpm**
refs: #168

### CODE REVIEW

**Comment by pxpm** [comment]
@tabacitu could we try to figure out why in online demo it's not broken but it's broken in repository ?

**Comment by tabacitu** [comment]
@pxpm I believe it's because on localhost DebugBar is also installed. In my experience, when DebugBar is enabled, we get that error. When it's disabled, it works fine.

Does this PR make it work on `localhost` with DebugBar enabled? Was this it?! I've wanted a fix for this for a while now 🥳

**Comment by pxpm** [comment]
Indeed, this makes it work in localhost with debugbar enabled. 

But haven't tested without debugbar enabled. It should work just fine, the returned results are the same, I just forced the response to have json header.

**Comment by tabacitu** [comment]
This is brilliant @pxpm . So glad you found a way to fix this, it was bugging me for quite a while. I won't even ask how long it took to figure out that the problem was the content-type 🤣 🙄 

I think we'd better consider this a bug in Backpack\CRUD, rather than the Demo, and fix it there. Following the solution in this PR I've created https://github.com/Laravel-Backpack/CRUD/pull/3266 . Please check it out and let me if I should merge it. If we do merge it, it'll fix it for the demo but also for everybody else, so it'll render this PR obsolete.

**Pull request closed without merging**
